plugins {
    id 'com.android.application'
}

android {
    namespace 'com.coldoon11.actioncamplus'
    compileSdk 36

    defaultConfig {
        applicationId 'com.coldoon11.actioncamplus'
        minSdk 29
        targetSdk 35
        versionCode 7
        versionName '0.7.0'
    }

    packaging {
        jniLibs {
            pickFirsts += ['**/libc++_shared.so']
        }
    }
}

dependencies {
    implementation "org.videolan.android:libvlc-all:3.7.6"
    implementation "dev.ffmpegkit-maintained:ffmpeg-kit-full:8.1.7"
}
